name: Publish Public Package

on:
  release:
    types: [created]

jobs:
  publish:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: yarn install --immutable
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLIC_TOKEN}}
